name: Run isort

on:
  pull_request:
    branches: [ "master" ]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Installing packages dependency
        run: sudo apt-get update && sudo apt-get install -y libsystemd-dev
      - name: Installing python dependency
        run: pip install -r requirements.txt -r requirements.dev.txt
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements.dev.txt"
