name: Run mypy

on:
  pull_request:
    branches: [ "master" ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Installing packages dependency
        run: sudo apt-get update && sudo apt-get install -y libsystemd-dev
      - name: Installing python dependency
        run: pip install -r requirements.txt -r requirements.dev.txt
      - name: Run mypy
        run: py.test --mypy
